// Angular/src/app/components/add-task/add-task.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Task } from 'src/app/Task';
import { UiService } from 'src/app/services/ui.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.css']
})
export class AddTaskComponent implements OnInit {

  showAddTask: boolean = false;
  subscription: Subscription;

  text: string = "";
  day: string = "";
  reminder: boolean = false;

  @Output() onFormSubmit: EventEmitter<Task> = new EventEmitter();

  constructor(private uiService: UiService) {
    this.subscription = this.uiService
      .onToggle()
      .subscribe(value => (this.showAddTask = value));
  }

  ngOnInit(): void {
  }

  onSubmit() {
    if (!this.text) {
      alert("Please Add a task");
      return;
    }

    const newTask: Task = {
      text: this.text,
      day: this.day,
      reminder: this.reminder
    }

    this.onFormSubmit.emit(newTask);

    this.text = '';
    this.reminder = false;
    this.day = '';

  }
}

<form *ngIf="showAddTask" class="add-form" (ngSubmit)="onSubmit()">
    <div class="form-control">
        <label for="text">Task</label>
        <input type="text" name="text" id="text" [(ngModel)]="text" placeholder="add new task">
    </div>
    <div class="form-control">
        <label for="day">Day & Time</label>
        <input type="text" name="day" [(ngModel)]="day" id="day" placeholder="add day & time">
    </div>

    <div class="form-control form-control-check">
        <label for="reminder">Reminder</label>
        <input type="checkbox" name="reminder" [(ngModel)]="reminder" id="reminder">
    </div>

    <input type="submit" value="Save Task" class="btn btn-block">
</form>

// React/src/components/AddTask.js
import { useState } from "react";

const AddTask = ({ onAdd }) => {
  const [text, setText] = useState("");
  const [day, setDay] = useState("");
  const [reminder, setReminder] = useState(false);

  const onSubmit = (e) => {
    e.preventDefault();

    if (!text) {
      alert("Please add a task");
    }

    onAdd({ text, day, reminder });

    setText("");
    setDay("");
    setReminder(false);
  };

  return (
    <form className="add-form" onSubmit={onSubmit}>
      <div className="form-control">
        <label>Task</label>
        <input
          type="text"
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Add Task"
        />
      </div>

      <div className="form-control">
        <label>Day & Time</label>
        <input
          type="text"
          value={day}
          onChange={(e) => setDay(e.target.value)}
          placeholder="Add Day"
        />
      </div>

      <div className="form-control form-control-check">
        <label>Set Reminder</label>
        <input
          checked={reminder}
          type="checkbox"
          value={reminder}
          onChange={(e) => setReminder(e.currentTarget.checked)}
        />
      </div>

      <input className="btn btn-block" type="submit" value="Save Task" />
    </form>
  );
};

export default AddTask;
